version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - esdata:/usr/share/elasticsearch/data

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - PORT=${PORT}
      - GITHUB_API_KEY=${GITHUB_API_KEY}
      - ES_HOST=host.docker.internal
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

volumes:
  esdata:
